# Generated by Django 4.0.5 on 2022-06-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_list',
            name='status',
        ),
    ]
