# Generated by Django 4.0.5 on 2022-06-16 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todolist.status'),
            preserve_default=False,
        ),
    ]
